export const PARDJS_AUTH_SERVICE_BASE_URL = process.env.PARDJS_AUTH_SERVICE_BASE_URL;
export const PARDJS_AUTH_SERVICE_GRPC_URL = process.env.PARDJS_AUTH_SERVICE_GRPC_URL;
export const GREEN_LIGHT_WITHOUT_USER_SERVICE = process.env.GREEN_LIGHT_WITHOUT_USER_SERVICE === 'true' || false;
