export * from './grpc-auth-service.interface'
export * from './hero-by-id.interface'
export * from './hero-service.interface'
export * from './hero.interface'
export * from './jwt-payload.interface'
export * from './pard-grpc-error.interface'